name: pecunia
description: A Personal Finance Management App.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Remote
  supabase_flutter: ^1.6.2

  # Navigation
  go_router: ^6.5.0

  # Business Logic, Dependency Injection
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.1.1

  # Data classes
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  uuid:

  # Local Storage
  drift: ^2.8.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  drift_db_viewer: ^2.0.0

  # Functional Programming
  fpdart: ^0.6.0

  # Connectivity
  internet_connection_checker_plus: ^1.0.1

  # Icons
  cupertino_icons: ^1.0.2

  # Convenience
  reactive_forms: ^15.0.0
  screwdriver: ^4.1.0

  # Testing
  mocktail: ^0.3.0

  # Logging
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator:

  # Linting
  custom_lint:
  riverpod_lint: ^1.3.2
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

  # Local Storage
  drift_dev: ^2.8.3

flutter:
  uses-material-design: true
