name: pecunia
description: A Personal Finance Management App.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Remote
  supabase_flutter: ^1.6.2

  # Navigation
  go_router: ^6.5.0

  # Business Logic, Dependency Injection
  hooks_riverpod:
  flutter_hooks:
  riverpod_annotation:

  # Data classes/management
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  uuid:
  money2: ^3.4.1
  intl: ^0.18.1

  # Local Storage
  drift: ^2.12.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  drift_db_viewer: ^2.0.0

  # Functional Programming
  fpdart: ^0.6.0

  # Connectivity
  internet_connection_checker_plus: ^1.0.1

  # Icons and Splash
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1

  # Dialogs
  flutter_easy_dialogs: ^2.0.8+7
  positioned_dialog_manager: ^1.0.5+1
  full_screen_dialog_manager: ^1.0.4+1

  # UI and Animations
  simple_animations: ^5.0.2
  bottom_nav_layout: ^3.0.10
  google_nav_bar: ^5.0.6
  sliver_app_bar_builder: ^1.1.0
  flutter_gradient_animation_text: ^1.0.2
  animated_text_kit: ^4.2.2
  sprung: ^3.0.1
  flutter_expandable_fab: ^2.0.0
  fl_chart: ^0.63.0

  # Convenience
  screwdriver: ^4.1.0
  flex_color_picker: ^3.3.0
  flutter_iconpicker: ^3.2.4
  email_validator: ^2.1.17

  # Testing
  mocktail: ^0.3.0
  clock: ^1.1.1

  # Logging
  logger: ^1.4.0
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator:

  # Linting
  custom_lint:
  riverpod_lint: ^1.3.2
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

  # Local Storage
  drift_dev: ^2.8.3

  # Package Name
  change_app_package_name: ^1.1.0

  # App Icons
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#1C1B1F"
  adaptive_icon_foreground: "assets/app_icon/dev_bg.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/dev_bg.png"

flutter_native_splash:
  color: "#1C1B1F"
  image: "assets/app_icon/dev_transparent.png"

  android_12:
    image: assets/app_icon/dev_transparent.png
    icon_background_color: "#1C1B1F"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/dev_transparent.png
    - assets/app_icon/icon_transparent.png

  fonts:
    - family: Subjectivity
      fonts:
        - asset: fonts/Subjectivity-Black.otf
          weight: 900
        - asset: fonts/Subjectivity-BlackSlanted.otf
          weight: 900
          style: italic
        - asset: fonts/Subjectivity-Bold.otf
          weight: 700
        - asset: fonts/Subjectivity-BoldSlanted.otf
          weight: 700
          style: italic
        - asset: fonts/Subjectivity-ExtraBold.otf
          weight: 800
        - asset: fonts/Subjectivity-ExtraBoldSlanted.otf
          weight: 800
          style: italic
        - asset: fonts/Subjectivity-Light.otf
          weight: 300
        - asset: fonts/Subjectivity-LightSlanted.otf
          weight: 300
          style: italic
        - asset: fonts/Subjectivity-Medium.otf
          weight: 500
        - asset: fonts/Subjectivity-MediumSlanted.otf
          weight: 500
          style: italic
        - asset: fonts/Subjectivity-Regular.otf
          weight: 400
        - asset: fonts/Subjectivity-RegularSlanted.otf
          weight: 400
          style: italic
        - asset: fonts/Subjectivity-Thin.otf
          weight: 100
        - asset: fonts/Subjectivity-ThinSlanted.otf
          weight: 100
          style: italic
